name: Atualizar FIIs

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

# 🔥 PERMISSÃO PRA FAZER PUSH
permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repo
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar Playwright
        run: |
          pip install playwright
          playwright install chromium

      - name: Rodar scraping
        run: python scraper.py

      - name: Commit JSON
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"
          git add data/fii.json
          git commit -m "update fii data" || echo "sem mudanças"
          git push
